version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: diamond-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  valuation-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diamond-api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # HTTP endpoint
      - ASPNETCORE_URLS=http://+:8080
      # HTTPS endpoint (Kestrel)
      - Kestrel__Endpoints__Https__Url=https://+:8443
      - Kestrel__Endpoints__Https__Certificate__Path=/https/aspnetapp.pfx
      - Kestrel__Endpoints__Https__Certificate__Password=MyStrongPfxPwd!123
      # DB connection (container-to-container)
      - ConnectionStrings__SqlServer=Server=sqlserver,1433;Database=DiamondDb;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True
    volumes:
      # ❗ DÙNG ĐƯỜNG DẪN TUYỆT ĐỐI (Windows dùng '/')
      - E:/Diamond-Valuation-Service/https:/https:ro
    ports:
      - "8080:8080"  # HTTP
      - "8443:8443"  # HTTPS
    restart: unless-stopped

volumes:
  sql_data:
