version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - C:\sql-certs\sqlserver.pfx:/var/opt/mssql/secrets/sqlserver.pfx:ro
    ports:
      - "1433:1433"
