version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports: ["1433:1433"]
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P Your_password123 -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  invoice-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=InvoiceDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
    ports: ["8088:8080"]
