services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: diamond-rabbitmq
  #   ports:
  #     - "5672:5672" 
  #     - "15672:15672"  # web management UI
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   healthcheck:
  #     test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  inventory-service:
    build:
      context: .
      dockerfile: ./Inventory.Api/Dockerfile
    environment:
      - ConnectionStrings__InventoryConnection=Server=sqlserver,1433;Database=DiamondInventoryDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:8080
      # - RabbitMQ__HostName=rabbitmq
      # - RabbitMQ__Port=5672
      # - RabbitMQ__UserName=guest
      # - RabbitMQ__Password=guest
    ports:
      - "8081:8080"
    depends_on:
      sqlserver:
        condition: service_started
      # rabbitmq:
      #   condition: service_healthy
