services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dvs_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password_123
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$SA_PASSWORD -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 10

  content-api:
    build: .
    container_name: dvs_content_api
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver;Database=Diamond_Content;User Id=sa;Password=Your_strong_password_123;TrustServerCertificate=True;
      - Jwt__Key=super_secret_dev_key_change_me_please_1234567890
      - Jwt__Issuer=DVS.ContentService
      - Jwt__Audience=DVS.Clients
    ports:
      - "5143:8080"
