services:
  valuationrespon-api:
    build:
      context: .
      dockerfile: ValuationRespon.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=db;Database=ValuationResponDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: valuationrespon-sql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
