services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dv_sql_valuation
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
    ports:
      - "14335:1433"        # GHI CỨNG 14335
    restart: unless-stopped
