services:
    product.api:
        build:
            context: .
            dockerfile: Product.Api/Dockerfile
        depends_on:
            - sqlserver
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:8080
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProductDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
        ports:
            - "8081:8080"

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - sql_data:/var/opt/mssql

volumes:
    sql_data:
